image: maven:latest

variables:
  BUILD_PROPS: "-Dbuild.revision=$CI_COMMIT_SHA -Dbuild.branch=$CI_COMMIT_REF_NAME -Dbuild.number=$CI_PIPELINE_IID "
  MAVEN_CLI_OPTS: " --batch-mode -Dfile.encoding=UTF-8 -s .mvn/settings.xml -Dhttp.keepAlive=false -Dmaven.wagon.http.pool=false"

before_script:
  - export CI_JOB_TIMESTAMP="-Dbuild.timestamp=$(date --utc --iso-8601=seconds)"

java-11:
  stage: build
  image: $CI_REGISTRY_IMAGE/maven:3-jdk-11
  script:
    - mvn $MAVEN_CLI_OPTS $BUILD_PROPS $CI_JOB_TIMESTAMP verify
  retry: 2
  artifacts:
    name: java-11
    paths:
      - target/*.jar
      - target/*.zip
    reports:
      junit:
        - target/surefire-reports/*.xml
        - target/failsafe-reports/*.xml

java-11-openj9:
  stage: build
  image: $CI_REGISTRY_IMAGE/maven:3-jdk-11-openj9
  script:
    - mvn $MAVEN_CLI_OPTS $BUILD_PROPS $CI_JOB_TIMESTAMP verify
  retry: 2
  artifacts:
    name: java-11-openj9
    paths:
      - target/*.jar
    reports:
      junit:
        - target/surefire-reports/*.xml
        - target/failsafe-reports/*.xml

java8:
  stage: build
  image: $CI_REGISTRY_IMAGE/maven:3-jdk-8
  script:
    - mvn $MAVEN_CLI_OPTS $BUILD_PROPS $CI_JOB_TIMESTAMP verify
  retry: 2
  artifacts:
    name: java-8
    paths:
      - target/*.jar
    reports:
      junit:
        - target/surefire-reports/*.xml
        - target/failsafe-reports/*.xml

java-8-openj9:
  stage: build
  image: $CI_REGISTRY_IMAGE/maven:3-jdk-8-openj9
  script:
    - mvn $MAVEN_CLI_OPTS $BUILD_PROPS $CI_JOB_TIMESTAMP verify
  retry: 2
  artifacts:
    name: java-8-open-j9
    paths:
      - target/*.jar
    reports:
      junit:
        - target/surefire-reports/*.xml
        - target/failsafe-reports/*.xml

java-15:
  stage: build
  image: $CI_REGISTRY_IMAGE/maven:3-openjdk-15
  script:
    - mvn $MAVEN_CLI_OPTS $BUILD_PROPS $CI_JOB_TIMESTAMP verify
  retry: 2
  artifacts:
    when: on_failure
    name: java-15
    paths:
      - target/*
    reports:
      junit:
        - target/surefire-reports/*.xml
        - target/failsafe-reports/*.xml

java-16:
  stage: build
  image: $CI_REGISTRY_IMAGE/maven:3-openjdk-16
  script:
    - mvn $MAVEN_CLI_OPTS $BUILD_PROPS $CI_JOB_TIMESTAMP verify
  retry: 2
  artifacts:
    when: on_failure
    name: java-16
    paths:
      - target/*
    reports:
      junit:
        - target/surefire-reports/*.xml
        - target/failsafe-reports/*.xml

java-17:
  stage: build
  image: $CI_REGISTRY_IMAGE/maven:3-openjdk-17
  script:
    - mvn $MAVEN_CLI_OPTS $BUILD_PROPS $CI_JOB_TIMESTAMP verify
  retry: 2
  artifacts:
    when: on_failure
    name: java-17
    paths:
      - target/*
    reports:
      junit:
        - target/surefire-reports/*.xml
        - target/failsafe-reports/*.xml

deploy:
  stage: deploy
  image: $CI_REGISTRY_IMAGE/maven:3-jdk-11
  dependencies:
    - java-11
  script:
    - export PROJECT_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
    - mvn $MAVEN_CLI_OPTS  deploy:deploy-file -Dfile=target/validationtool-${PROJECT_VERSION}.zip -DgroupId=kosit -DartifactId=validator -Dclassifier="distribution" -Dversion=${PROJECT_VERSION} -Dpackaging=zip -DrepositoryId="gitlab-maven" -Durl=https://projekte.kosit.org/api/v4/projects/7/packages/maven
    - mvn $MAVEN_CLI_OPTS  deploy:deploy-file -Dfile=target/validationtool-${PROJECT_VERSION}.jar -DgroupId=kosit -DartifactId=validator -Dversion=${PROJECT_VERSION} -Dpackaging=jar -DrepositoryId="gitlab-maven" -Durl=https://projekte.kosit.org/api/v4/projects/7/packages/maven
    - mvn $MAVEN_CLI_OPTS  deploy:deploy-file -Dfile=target/validationtool-${PROJECT_VERSION}-javadoc.jar -DgroupId=kosit -DartifactId=validator -Dclassifier="javadoc" -Dversion=${PROJECT_VERSION} -Dpackaging=zip -DrepositoryId="gitlab-maven" -Durl=https://projekte.kosit.org/api/v4/projects/7/packages/maven
    - mvn $MAVEN_CLI_OPTS  deploy:deploy-file -Dfile=target/validationtool-${PROJECT_VERSION}-standalone.jar -DgroupId=kosit -DartifactId=validator -Dclassifier="standalone" -Dversion=${PROJECT_VERSION} -Dpackaging=jar -DrepositoryId="gitlab-maven" -Durl=https://projekte.kosit.org/api/v4/projects/7/packages/maven
    - mvn $MAVEN_CLI_OPTS  deploy:deploy-file -Dfile=target/validationtool-${PROJECT_VERSION}-java8-standalone.jar -DgroupId=kosit -DartifactId=validator -Dclassifier="java8-standalone" -Dversion=${PROJECT_VERSION} -Dpackaging=jar -DrepositoryId="gitlab-maven" -Durl=https://projekte.kosit.org/api/v4/projects/7/packages/maven
    - mvn $MAVEN_CLI_OPTS  deploy:deploy-file -Dfile=target/validationtool-${PROJECT_VERSION}-sources.jar -DgroupId=kosit -DartifactId=validator -Dclassifier="sources" -Dversion=${PROJECT_VERSION} -Dpackaging=jar -DrepositoryId="gitlab-maven" -Durl=https://projekte.kosit.org/api/v4/projects/7/packages/maven
  when: manual

create-build-image:
  stage: deploy
  image: docker:latest
  needs: [ ]
  services:
    - docker:dind
  script:
    - apk add bash
    - bash .mvn/createBuildImages.sh
  when: manual


