image: maven:latest

variables:
  MAVEN_CLI_OPTS: " --batch-mode -Dmaven.repo.local=repository -Dfile.encoding=UTF-8"

cache:
  paths:
    - repository

build-java-latest:
  stage: build
  script:
    - mvn $MAVEN_CLI_OPTS  verify
  artifacts:
    name: java-latest
    paths:
      - target/*.jar
    reports:
      junit:
        - target/surefire-reports/*.xml
        - target/failsafe-reports/*.xml

build-java8:
  stage: build
  image: maven:3-jdk-8-alpine
  script:
    - mvn $MAVEN_CLI_OPTS  verify
  artifacts:
    name: java8
    paths:
      - target/*.jar
    reports:
      junit:
        - target/surefire-reports/*.xml
        - target/failsafe-reports/*.xml
